### ISSUE TITLE
No module named spacy.lang.la

### ISSUE THREAD

**Issue by Motorrat** [diyclassics/latin-spacy-models#1]
Great initiative to make Latin model available. I am proud to open the very first issue against it :-) 

I have downloaded and installed the model with pip install in my virtual environment "full".

The model directory is symlinked from both `spacy/data/la_latin_spacy_model` and `spacy/data/la`

`ln -s /home/user/venv/full/lib/python3.6/site-packages/la_latin_spacy_model  /home/user/venv/full/lib/python3.6/site-packages/spacy/data/la_latin_spacy_model`
`ln -s /home/user/venv/full/lib/python3.6/site-packages/la_latin_spacy_model  /home/user/venv/full/lib/python3.6/site-packages/spacy/data/la`

Yet spacy cannot load it:

```
python 
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy_pipe = spacy.load('la_latin_spacy_model')
Traceback (most recent call last):
  File "/home/user/venv/full/lib/python3.6/site-packages/spacy/util.py", line 70, in get_lang_class
    module = importlib.import_module(".lang.%s" % lang, "spacy")
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'spacy.lang.la'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/venv/full/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/user/venv/full/lib/python3.6/site-packages/spacy/util.py", line 132, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/user/venv/full/lib/python3.6/site-packages/spacy/util.py", line 149, in load_model_from_link
    return cls.load(**overrides)
  File "/home/user/venv/full/lib/python3.6/site-packages/spacy/data/la_latin_spacy_model/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/user/venv/full/lib/python3.6/site-packages/spacy/util.py", line 196, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/user/venv/full/lib/python3.6/site-packages/spacy/util.py", line 166, in load_model_from_path
    cls = get_lang_class(lang)
  File "/home/user/venv/full/lib/python3.6/site-packages/spacy/util.py", line 72, in get_lang_class
    raise ImportError(Errors.E048.format(lang=lang, err=err))
ImportError: [E048] Can't import language la from spacy.lang: No module named 'spacy.lang.la'
>>> 
```

**Comment by diyclassics** [comment]
Thanks! And happy to try to figure this out...

I haven't pushed the Latin code to the main distribution yet. (A bit circular—but I'm using the preliminary models to build out the language parameters which in turn are being used to improve the models etc.) So you need to install spaCy from my fork/branch to get access to a spacy.lang.la module.

The only way I could get this to work was to follow the compile from source directions here: https://spacy.io/usage/#source. Change the second line to:

- git clone --branch latin-dev https://github.com/diyclassics/spaCy.git

(And if you are already in an env you probably won't need those steps.)

Let me know if that works and I will update the README.md.

**Comment by sarcanon** [comment]
I have no idea whether this is relevant or not, but apparently there are some backward incompatibility issues in the latest versions of spacy (I show 2.2.3 as latest). Documented here: https://spacy.io/usage/v2-2#incompat

FWIW, I get a bit further than @motorrat. I fail with following:

```
Traceback (most recent call last):
  File "c:/Users/Scott/Desktop/Python/test.py", line 2, in <module>
    nlp = spacy.load('la_latin_spacy_model')
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python38\Lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python38\Lib\site-packages\spacy\util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python38\Lib\site-packages\spacy\util.py", line 185, in load_model_from_package   
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python38\Lib\site-packages\la_latin_spacy_model\__init__.py", line 12, in load    
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python38\Lib\site-packages\spacy\util.py", line 228, in load_model_from_init_py   
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python38\Lib\site-packages\spacy\util.py", line 196, in load_model_from_path      
    cls = get_lang_class(lang)
  File "C:\Users\Scott\AppData\Local\Programs\Python\Python38\Lib\site-packages\spacy\util.py", line 77, in get_lang_class
    set_lang_class(lang, getattr(module, module.__all__[0]))
AttributeError: module 'spacy.lang.la' has no attribute '__all__'

```

**Comment by diyclassics** [comment]
@sarcanon Thanks for bringing this to my attention—haven't had much time to commit to this recently, but will take a look.

**Comment by pkrefta** [comment]
Hey @diyclassics 

I've tried to clone latin-dev branch but It's not in the repo. Where can I find it ? Also - are there any plans to revive this project ? 😃

**Comment by diyclassics** [comment]
Closing this issue since it pertains to an older version of spaCy. Model for spaCy v.3 now available in the repo.
